########################################################################################
#                                                                                      #
#                      /$$$$$$$  /$$                     /$$                           #
#                     | $$__  $$|__/                    | $$                           #
#                     | $$  \ $$ /$$ /$$   /$$  /$$$$$$ | $$                           #
#                     | $$$$$$$/| $$|  $$ /$$/ /$$__  $$| $$                           #
#                     | $$____/ | $$ \  $$$$/ | $$$$$$$$| $$                           #
#                     | $$      | $$  >$$  $$ | $$_____/| $$                           #
#                     | $$      | $$ /$$/\  $$|  $$$$$$$| $$                           #
#                     |__/      |__/|__/  \__/ \_______/|__/                           #
#                                                                                      #
########################################################################################
#                                                                                      #
#                              PixelEdge Essentials                                    #
#                                   Ver 0.0.1                                          #
########################################################################################

#================================== Settings ===========================================

main-prefix: '&7[&bPixeledgeEssentials&7]'
pixeleffect-prefix: '&7&l[&f&lPixelEffects&7&l]'

#================================ Custom Effects =======================================

rage: true
fury: true
regen: true

effect-gui: true